-- ============================================
-- NovaMind Update 36.0: Attendance System Setup
-- ============================================
-- Run this SQL in Supabase Dashboard → SQL Editor

-- 1. Create class_coordinates table (Teacher sets location)
CREATE TABLE IF NOT EXISTS public.class_coordinates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  subject TEXT NOT NULL,
  day_of_week INT NOT NULL, -- 1=Monday, 7=Sunday
  latitude FLOAT8 NOT NULL,
  longitude FLOAT8 NOT NULL,
  set_by TEXT DEFAULT 'Teacher',
  UNIQUE(subject, day_of_week)
);

-- 2. Add proof_url column to attendance_logs (if not exists)
ALTER TABLE public.attendance_logs 
ADD COLUMN IF NOT EXISTS proof_url TEXT;

-- 3. Add latitude and longitude to attendance_logs (if not exists)
ALTER TABLE public.attendance_logs 
ADD COLUMN IF NOT EXISTS latitude FLOAT8;

ALTER TABLE public.attendance_logs 
ADD COLUMN IF NOT EXISTS longitude FLOAT8;

-- 4. Enable Row Level Security
ALTER TABLE public.class_coordinates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies for class_coordinates
DROP POLICY IF EXISTS "Public Read Coords" ON public.class_coordinates;
CREATE POLICY "Public Read Coords" 
ON public.class_coordinates FOR SELECT 
TO anon 
USING (true);

DROP POLICY IF EXISTS "Public Write Coords" ON public.class_coordinates;
CREATE POLICY "Public Write Coords" 
ON public.class_coordinates FOR INSERT 
TO anon 
WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Coords" ON public.class_coordinates;
CREATE POLICY "Public Update Coords" 
ON public.class_coordinates FOR UPDATE 
TO anon 
USING (true);

-- 6. Create Policies for attendance_logs
DROP POLICY IF EXISTS "Public Read Attendance" ON public.attendance_logs;
CREATE POLICY "Public Read Attendance" 
ON public.attendance_logs FOR SELECT 
TO anon 
USING (true);

DROP POLICY IF EXISTS "Public Insert Attendance" ON public.attendance_logs;
CREATE POLICY "Public Insert Attendance" 
ON public.attendance_logs FOR INSERT 
TO anon 
WITH CHECK (true);

-- 7. Enable Realtime for both tables
ALTER PUBLICATION supabase_realtime ADD TABLE class_coordinates;
ALTER PUBLICATION supabase_realtime ADD TABLE attendance_logs;

-- 8. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_class_coords_subject_day 
ON public.class_coordinates(subject, day_of_week);

CREATE INDEX IF NOT EXISTS idx_attendance_student_date 
ON public.attendance_logs(student_id, timestamp);

CREATE INDEX IF NOT EXISTS idx_attendance_subject_date 
ON public.attendance_logs(subject, timestamp);

-- ============================================
-- Verification Queries
-- ============================================

-- Check if tables exist
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('class_coordinates', 'attendance_logs');

-- Check columns in attendance_logs
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'attendance_logs' 
AND table_schema = 'public';

-- Check policies
SELECT schemaname, tablename, policyname 
FROM pg_policies 
WHERE tablename IN ('class_coordinates', 'attendance_logs');

-- ============================================
-- Sample Data (Optional - for testing)
-- ============================================

-- Insert sample class location
-- INSERT INTO public.class_coordinates (subject, day_of_week, latitude, longitude, set_by)
-- VALUES ('IP', 4, 15.4789, 78.4886, 'Teacher');

-- ============================================
-- IMPORTANT: Storage Bucket Setup
-- ============================================
-- You MUST create the storage bucket manually:
-- 1. Go to Supabase Dashboard → Storage
-- 2. Click "New Bucket"
-- 3. Name: attendance_proofs
-- 4. Public bucket: ✅ CHECKED
-- 5. Click "Save"
-- 6. Go to Policies tab
-- 7. Add policy: "Give full access to everyone"
--    - Policy name: Public Access
--    - Allowed operations: SELECT, INSERT, UPDATE, DELETE
--    - Target roles: public
--    - USING expression: true
--    - WITH CHECK expression: true
-- ============================================
