import 'package:flutter/material.dart';

class RoadmapStep {
  final String title;
  final String description;
  final String duration;
  final List<String> topics;
  final List<String> resources;

  RoadmapStep({
    required this.title,
    required this.description,
    required this.duration,
    required this.topics,
    required this.resources,
  });
}

class TechRoadmap {
  final String title;
  final String description;
  final String category;
  final String duration;
  final IconData icon;
  final Color color;
  final List<RoadmapStep> steps;

  TechRoadmap({
    required this.title,
    required this.description,
    required this.category,
    required this.duration,
    required this.icon,
    required this.color,
    required this.steps,
  });
}

class RoadmapRepository {
  static final List<TechRoadmap> allRoadmaps = [
    // Frontend Development (Detailed)
    TechRoadmap(
      title: 'Frontend Developer',
      description: 'Complete frontend development roadmap from basics to advanced',
      category: 'Web Development',
      duration: '6-9 months',
      icon: Icons.web,
      color: Colors.blue,
      steps: [
        RoadmapStep(
          title: 'Internet & Web Basics',
          description: 'Understand how the internet and web work',
          duration: '1 week',
          topics: [
            'How does the internet work?',
            'What is HTTP/HTTPS?',
            'DNS and how it works',
            'Domain names',
            'Hosting basics',
            'Browsers and how they work',
          ],
          resources: [
            'MDN Web Docs - How the Web Works',
            'CS50 Web Programming',
            'roadmap.sh/frontend',
          ],
        ),
        RoadmapStep(
          title: 'HTML Fundamentals',
          description: 'Master HTML5 and semantic markup',
          duration: '2-3 weeks',
          topics: [
            'Basic HTML syntax',
            'Semantic HTML5 elements',
            'Forms and validations',
            'Accessibility basics (ARIA)',
            'SEO basics',
            'Best practices',
          ],
          resources: [
            'MDN HTML Guide',
            'web.dev Learn HTML',
            'HTML5 Doctor',
          ],
        ),
        RoadmapStep(
          title: 'CSS Fundamentals',
          description: 'Learn CSS styling and layouts',
          duration: '3-4 weeks',
          topics: [
            'CSS syntax and selectors',
            'Box model',
            'Positioning (static, relative, absolute, fixed, sticky)',
            'Display and visibility',
            'Flexbox layout',
            'Grid layout',
            'Responsive design',
            'Media queries',
          ],
          resources: [
            'CSS-Tricks',
            'Flexbox Froggy',
            'Grid Garden',
            'web.dev Learn CSS',
          ],
        ),
        RoadmapStep(
          title: 'JavaScript Basics',
          description: 'Learn JavaScript fundamentals',
          duration: '4-6 weeks',
          topics: [
            'Variables (let, const, var)',
            'Data types',
            'Operators',
            'Conditionals',
            'Loops',
            'Functions',
            'Arrays and objects',
            'String methods',
          ],
          resources: [
            'JavaScript.info',
            'MDN JavaScript Guide',
            'Eloquent JavaScript',
          ],
        ),
        RoadmapStep(
          title: 'JavaScript Advanced',
          description: 'Master advanced JavaScript concepts',
          duration: '4-6 weeks',
          topics: [
            'ES6+ features',
            'Arrow functions',
            'Destructuring',
            'Spread/rest operators',
            'Template literals',
            'Promises',
            'Async/await',
            'Fetch API',
            'Closures',
            'Prototypes',
            'this keyword',
          ],
          resources: [
            'You Don\'t Know JS',
            'JavaScript30',
            'FreeCodeCamp',
          ],
        ),
        RoadmapStep(
          title: 'DOM Manipulation',
          description: 'Work with the Document Object Model',
          duration: '2-3 weeks',
          topics: [
            'Selecting elements',
            'Manipulating elements',
            'Event listeners',
            'Event delegation',
            'Creating elements',
            'Modifying styles',
            'Working with forms',
          ],
          resources: [
            'MDN DOM Guide',
            'JavaScript DOM Crash Course',
            'DOM Enlightenment',
          ],
        ),
        RoadmapStep(
          title: 'Version Control (Git)',
          description: 'Learn Git and GitHub',
          duration: '1-2 weeks',
          topics: [
            'Git basics',
            'Commits',
            'Branches',
            'Merging',
            'Pull requests',
            'GitHub workflow',
            'Git best practices',
          ],
          resources: [
            'Pro Git Book',
            'GitHub Learning Lab',
            'Git Immersion',
          ],
        ),
        RoadmapStep(
          title: 'Package Managers',
          description: 'Learn npm and yarn',
          duration: '1 week',
          topics: [
            'npm basics',
            'package.json',
            'Installing packages',
            'Scripts',
            'Semantic versioning',
            'yarn alternative',
          ],
          resources: [
            'npm Documentation',
            'yarn Documentation',
            'Package Manager Guide',
          ],
        ),
        RoadmapStep(
          title: 'CSS Preprocessors',
          description: 'Learn Sass/SCSS',
          duration: '2 weeks',
          topics: [
            'Variables',
            'Nesting',
            'Mixins',
            'Functions',
            'Partials and imports',
            'Inheritance',
          ],
          resources: [
            'Sass Documentation',
            'Sass Guidelines',
            'Sass Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Build Tools',
          description: 'Learn module bundlers and task runners',
          duration: '2-3 weeks',
          topics: [
            'Webpack basics',
            'Vite',
            'Parcel',
            'Module bundling',
            'Code splitting',
            'Hot module replacement',
          ],
          resources: [
            'Webpack Documentation',
            'Vite Guide',
            'Frontend Build Tools',
          ],
        ),
        RoadmapStep(
          title: 'React Framework',
          description: 'Master React.js',
          duration: '8-10 weeks',
          topics: [
            'JSX',
            'Components',
            'Props',
            'State',
            'Lifecycle methods',
            'Hooks (useState, useEffect, useContext, etc.)',
            'React Router',
            'Forms in React',
            'Context API',
            'Performance optimization',
          ],
          resources: [
            'React Official Docs',
            'React Tutorial',
            'Epic React',
            'Scrimba React',
          ],
        ),
        RoadmapStep(
          title: 'State Management',
          description: 'Learn Redux or Zustand',
          duration: '2-3 weeks',
          topics: [
            'Redux basics',
            'Actions and reducers',
            'Store',
            'Redux Toolkit',
            'Zustand alternative',
            'When to use state management',
          ],
          resources: [
            'Redux Documentation',
            'Redux Toolkit',
            'Zustand Docs',
          ],
        ),
        RoadmapStep(
          title: 'TypeScript',
          description: 'Add type safety to JavaScript',
          duration: '3-4 weeks',
          topics: [
            'TypeScript basics',
            'Types and interfaces',
            'Generics',
            'Enums',
            'Type assertions',
            'TypeScript with React',
          ],
          resources: [
            'TypeScript Handbook',
            'TypeScript Deep Dive',
            'Total TypeScript',
          ],
        ),
        RoadmapStep(
          title: 'Testing',
          description: 'Write tests for your code',
          duration: '2-3 weeks',
          topics: [
            'Jest basics',
            'Unit testing',
            'React Testing Library',
            'Integration tests',
            'E2E testing with Cypress',
            'Test-driven development',
          ],
          resources: [
            'Jest Documentation',
            'Testing Library',
            'Cypress Docs',
          ],
        ),
        RoadmapStep(
          title: 'Web Performance',
          description: 'Optimize your applications',
          duration: '2 weeks',
          topics: [
            'Performance metrics',
            'Lighthouse',
            'Code splitting',
            'Lazy loading',
            'Image optimization',
            'Caching strategies',
          ],
          resources: [
            'web.dev Performance',
            'Web Performance Guide',
            'Chrome DevTools',
          ],
        ),
      ],
    ),

    // Backend Development (Detailed)
    TechRoadmap(
      title: 'Backend Developer',
      description: 'Complete backend development roadmap',
      category: 'Web Development',
      duration: '7-10 months',
      icon: Icons.dns,
      color: Colors.green,
      steps: [
        RoadmapStep(
          title: 'Internet Basics',
          description: 'Understand internet fundamentals',
          duration: '1 week',
          topics: [
            'How does the internet work?',
            'HTTP/HTTPS protocols',
            'TCP/IP',
            'DNS',
            'APIs',
            'REST architecture',
          ],
          resources: [
            'MDN HTTP Guide',
            'roadmap.sh/backend',
            'CS50 Network',
          ],
        ),
        RoadmapStep(
          title: 'Programming Language (Node.js)',
          description: 'Learn JavaScript/Node.js for backend',
          duration: '6-8 weeks',
          topics: [
            'JavaScript fundamentals',
            'Node.js basics',
            'npm and package management',
            'Asynchronous programming',
            'Event loop',
            'Streams and buffers',
            'File system operations',
          ],
          resources: [
            'Node.js Documentation',
            'Node.js Best Practices',
            'The Net Ninja Node.js',
          ],
        ),
        RoadmapStep(
          title: 'Version Control',
          description: 'Master Git and GitHub',
          duration: '1-2 weeks',
          topics: [
            'Git fundamentals',
            'Branching strategies',
            'Pull requests',
            'Code reviews',
            'Git workflows',
            'GitHub Actions basics',
          ],
          resources: [
            'Pro Git Book',
            'GitHub Learning Lab',
            'Atlassian Git Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Relational Databases',
          description: 'Learn SQL and PostgreSQL',
          duration: '4-6 weeks',
          topics: [
            'Database fundamentals',
            'SQL syntax',
            'CRUD operations',
            'Joins',
            'Indexes',
            'Transactions',
            'Normalization',
            'PostgreSQL specifics',
          ],
          resources: [
            'PostgreSQL Tutorial',
            'SQL Zoo',
            'Mode SQL Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'NoSQL Databases',
          description: 'Learn MongoDB',
          duration: '3-4 weeks',
          topics: [
            'NoSQL concepts',
            'MongoDB basics',
            'Collections and documents',
            'Queries',
            'Aggregation',
            'Indexing',
            'Mongoose ODM',
          ],
          resources: [
            'MongoDB University',
            'MongoDB Documentation',
            'Mongoose Docs',
          ],
        ),
        RoadmapStep(
          title: 'APIs (REST)',
          description: 'Build RESTful APIs',
          duration: '4-6 weeks',
          topics: [
            'REST principles',
            'HTTP methods',
            'Status codes',
            'Express.js framework',
            'Routing',
            'Middleware',
            'Error handling',
            'API versioning',
          ],
          resources: [
            'Express.js Guide',
            'REST API Tutorial',
            'API Design Best Practices',
          ],
        ),
        RoadmapStep(
          title: 'Authentication & Authorization',
          description: 'Secure your applications',
          duration: '3-4 weeks',
          topics: [
            'Authentication vs Authorization',
            'JWT tokens',
            'OAuth 2.0',
            'Session management',
            'Password hashing (bcrypt)',
            'Role-based access control',
            'Security best practices',
          ],
          resources: [
            'JWT.io',
            'OAuth 2.0 Guide',
            'OWASP Security',
          ],
        ),
        RoadmapStep(
          title: 'Caching',
          description: 'Implement caching strategies',
          duration: '2 weeks',
          topics: [
            'Caching concepts',
            'Redis basics',
            'Cache strategies',
            'CDN',
            'Server-side caching',
            'Client-side caching',
          ],
          resources: [
            'Redis Documentation',
            'Caching Best Practices',
            'Redis University',
          ],
        ),
        RoadmapStep(
          title: 'Testing',
          description: 'Write backend tests',
          duration: '3-4 weeks',
          topics: [
            'Unit testing',
            'Integration testing',
            'Jest/Mocha',
            'Supertest for APIs',
            'Test coverage',
            'TDD approach',
          ],
          resources: [
            'Jest Documentation',
            'Testing Node.js Apps',
            'Test-Driven Development',
          ],
        ),
        RoadmapStep(
          title: 'GraphQL (Optional)',
          description: 'Alternative to REST',
          duration: '3-4 weeks',
          topics: [
            'GraphQL basics',
            'Queries and mutations',
            'Schema design',
            'Apollo Server',
            'Resolvers',
            'GraphQL vs REST',
          ],
          resources: [
            'GraphQL Documentation',
            'Apollo Server Docs',
            'How to GraphQL',
          ],
        ),
        RoadmapStep(
          title: 'Containerization',
          description: 'Learn Docker',
          duration: '2-3 weeks',
          topics: [
            'Docker basics',
            'Containers vs VMs',
            'Dockerfile',
            'Docker Compose',
            'Container orchestration basics',
          ],
          resources: [
            'Docker Documentation',
            'Docker Mastery',
            'Play with Docker',
          ],
        ),
        RoadmapStep(
          title: 'Web Servers',
          description: 'Understand web servers',
          duration: '2 weeks',
          topics: [
            'Nginx basics',
            'Apache',
            'Reverse proxy',
            'Load balancing',
            'SSL/TLS',
          ],
          resources: [
            'Nginx Documentation',
            'Web Server Guide',
            'Let\'s Encrypt',
          ],
        ),
        RoadmapStep(
          title: 'Message Brokers',
          description: 'Learn RabbitMQ or Kafka',
          duration: '2-3 weeks',
          topics: [
            'Message queue concepts',
            'RabbitMQ basics',
            'Pub/Sub pattern',
            'Event-driven architecture',
            'Kafka basics',
          ],
          resources: [
            'RabbitMQ Tutorial',
            'Kafka Documentation',
            'Message Brokers Guide',
          ],
        ),
        RoadmapStep(
          title: 'Deployment',
          description: 'Deploy your applications',
          duration: '2-3 weeks',
          topics: [
            'Cloud platforms (AWS, Azure, GCP)',
            'CI/CD pipelines',
            'Environment variables',
            'Monitoring and logging',
            'Scaling strategies',
          ],
          resources: [
            'AWS Documentation',
            'Heroku Guide',
            'DigitalOcean Tutorials',
          ],
        ),
      ],
    ),

    // Full Stack Web Development
    TechRoadmap(
      title: 'Full Stack Web Development',
      description: 'Complete path from frontend to backend development',
      category: 'Web Development',
      duration: '10-12 months',
      icon: Icons.web,
      color: Colors.indigo,
      steps: [
        RoadmapStep(
          title: 'HTML & CSS Basics',
          description: 'Learn the foundation of web development',
          duration: '2-3 weeks',
          topics: [
            'HTML5 semantic elements',
            'CSS selectors and properties',
            'Flexbox and Grid layouts',
            'Responsive design',
            'CSS animations',
          ],
          resources: [
            'MDN Web Docs',
            'freeCodeCamp',
            'CSS-Tricks',
          ],
        ),
        RoadmapStep(
          title: 'JavaScript Fundamentals',
          description: 'Master the language of the web',
          duration: '4-6 weeks',
          topics: [
            'Variables, data types, operators',
            'Functions and scope',
            'Arrays and objects',
            'DOM manipulation',
            'ES6+ features',
            'Async/await and Promises',
          ],
          resources: [
            'JavaScript.info',
            'Eloquent JavaScript',
            'MDN JavaScript Guide',
          ],
        ),
        RoadmapStep(
          title: 'Frontend Framework (React)',
          description: 'Build modern interactive UIs',
          duration: '6-8 weeks',
          topics: [
            'Components and Props',
            'State and Lifecycle',
            'Hooks (useState, useEffect)',
            'Context API',
            'React Router',
            'Form handling',
          ],
          resources: [
            'React Official Docs',
            'React Tutorial',
            'Scrimba React Course',
          ],
        ),
        RoadmapStep(
          title: 'Backend with Node.js',
          description: 'Server-side JavaScript development',
          duration: '6-8 weeks',
          topics: [
            'Node.js basics',
            'Express.js framework',
            'RESTful API design',
            'Middleware',
            'Authentication (JWT)',
            'Error handling',
          ],
          resources: [
            'Node.js Docs',
            'Express.js Guide',
            'The Net Ninja',
          ],
        ),
        RoadmapStep(
          title: 'Database Management',
          description: 'Store and manage data',
          duration: '3-4 weeks',
          topics: [
            'SQL basics (PostgreSQL)',
            'MongoDB (NoSQL)',
            'Database design',
            'CRUD operations',
            'Indexing and optimization',
          ],
          resources: [
            'PostgreSQL Tutorial',
            'MongoDB University',
            'Database Design Course',
          ],
        ),
        RoadmapStep(
          title: 'Deployment & DevOps',
          description: 'Deploy your applications',
          duration: '2-3 weeks',
          topics: [
            'Git and GitHub',
            'Docker basics',
            'CI/CD pipelines',
            'Cloud platforms (AWS/Heroku)',
            'Environment variables',
          ],
          resources: [
            'GitHub Learning Lab',
            'Docker Documentation',
            'AWS Free Tier',
          ],
        ),
      ],
    ),

    // Python Development
    TechRoadmap(
      title: 'Python Developer',
      description: 'From basics to advanced Python programming',
      category: 'Programming',
      duration: '4-6 months',
      icon: Icons.code,
      color: Colors.green,
      steps: [
        RoadmapStep(
          title: 'Python Basics',
          description: 'Learn Python fundamentals',
          duration: '3-4 weeks',
          topics: [
            'Variables and data types',
            'Control flow (if/else, loops)',
            'Functions and modules',
            'Lists, tuples, dictionaries',
            'File handling',
          ],
          resources: [
            'Python.org Tutorial',
            'Automate the Boring Stuff',
            'Codecademy Python',
          ],
        ),
        RoadmapStep(
          title: 'Object-Oriented Programming',
          description: 'Master OOP concepts',
          duration: '2-3 weeks',
          topics: [
            'Classes and objects',
            'Inheritance',
            'Polymorphism',
            'Encapsulation',
            'Magic methods',
          ],
          resources: [
            'Real Python OOP',
            'Python OOP Tutorial',
            'Corey Schafer YouTube',
          ],
        ),
        RoadmapStep(
          title: 'Data Structures & Algorithms',
          description: 'Essential CS concepts',
          duration: '6-8 weeks',
          topics: [
            'Arrays and linked lists',
            'Stacks and queues',
            'Trees and graphs',
            'Sorting algorithms',
            'Searching algorithms',
            'Time complexity',
          ],
          resources: [
            'LeetCode',
            'HackerRank',
            'GeeksforGeeks',
          ],
        ),
        RoadmapStep(
          title: 'Web Frameworks (Django/Flask)',
          description: 'Build web applications',
          duration: '6-8 weeks',
          topics: [
            'Django/Flask basics',
            'URL routing',
            'Templates',
            'Forms and validation',
            'Database ORM',
            'Authentication',
          ],
          resources: [
            'Django Documentation',
            'Flask Mega-Tutorial',
            'Django for Beginners',
          ],
        ),
        RoadmapStep(
          title: 'APIs and Testing',
          description: 'Build and test APIs',
          duration: '3-4 weeks',
          topics: [
            'REST API design',
            'Django REST Framework',
            'Unit testing',
            'Integration testing',
            'API documentation',
          ],
          resources: [
            'DRF Documentation',
            'pytest Documentation',
            'Test-Driven Development',
          ],
        ),
      ],
    ),

    // Mobile Development
    TechRoadmap(
      title: 'Flutter Mobile Development',
      description: 'Build cross-platform mobile apps',
      category: 'Mobile Development',
      duration: '5-7 months',
      icon: Icons.phone_android,
      color: Colors.cyan,
      steps: [
        RoadmapStep(
          title: 'Dart Programming',
          description: 'Learn Dart language basics',
          duration: '2-3 weeks',
          topics: [
            'Dart syntax',
            'Variables and types',
            'Functions',
            'Classes and OOP',
            'Async programming',
          ],
          resources: [
            'Dart.dev',
            'Dart Language Tour',
            'DartPad',
          ],
        ),
        RoadmapStep(
          title: 'Flutter Basics',
          description: 'Understand Flutter framework',
          duration: '4-6 weeks',
          topics: [
            'Widgets (Stateless/Stateful)',
            'Layouts (Row, Column, Stack)',
            'Material Design',
            'Navigation',
            'Forms and input',
          ],
          resources: [
            'Flutter.dev',
            'Flutter Cookbook',
            'Flutter Widget Catalog',
          ],
        ),
        RoadmapStep(
          title: 'State Management',
          description: 'Manage app state effectively',
          duration: '3-4 weeks',
          topics: [
            'Provider',
            'Riverpod',
            'Bloc pattern',
            'GetX',
            'State management best practices',
          ],
          resources: [
            'Provider Package',
            'Bloc Library',
            'Flutter State Management',
          ],
        ),
        RoadmapStep(
          title: 'Backend Integration',
          description: 'Connect to APIs and databases',
          duration: '4-5 weeks',
          topics: [
            'HTTP requests',
            'REST API integration',
            'Firebase',
            'Supabase',
            'Local storage (Hive/SQLite)',
          ],
          resources: [
            'Firebase Flutter',
            'Supabase Flutter',
            'HTTP Package Docs',
          ],
        ),
        RoadmapStep(
          title: 'Advanced Features',
          description: 'Add professional features',
          duration: '4-6 weeks',
          topics: [
            'Animations',
            'Custom painters',
            'Platform channels',
            'Push notifications',
            'In-app purchases',
          ],
          resources: [
            'Flutter Animations',
            'Flutter Platform Channels',
            'Firebase Cloud Messaging',
          ],
        ),
        RoadmapStep(
          title: 'Testing & Deployment',
          description: 'Test and publish your app',
          duration: '2-3 weeks',
          topics: [
            'Unit testing',
            'Widget testing',
            'Integration testing',
            'Play Store deployment',
            'App Store deployment',
          ],
          resources: [
            'Flutter Testing',
            'Play Console Guide',
            'App Store Connect',
          ],
        ),
      ],
    ),

    // Data Science
    TechRoadmap(
      title: 'Data Science & ML',
      description: 'Master data analysis and machine learning',
      category: 'Data Science',
      duration: '8-10 months',
      icon: Icons.analytics,
      color: Colors.purple,
      steps: [
        RoadmapStep(
          title: 'Python for Data Science',
          description: 'Python libraries for data work',
          duration: '4-6 weeks',
          topics: [
            'NumPy arrays',
            'Pandas DataFrames',
            'Matplotlib visualization',
            'Seaborn plots',
            'Jupyter Notebooks',
          ],
          resources: [
            'Kaggle Learn',
            'DataCamp',
            'Python Data Science Handbook',
          ],
        ),
        RoadmapStep(
          title: 'Statistics & Mathematics',
          description: 'Essential math for data science',
          duration: '6-8 weeks',
          topics: [
            'Descriptive statistics',
            'Probability',
            'Hypothesis testing',
            'Linear algebra',
            'Calculus basics',
          ],
          resources: [
            'Khan Academy Statistics',
            'StatQuest YouTube',
            '3Blue1Brown',
          ],
        ),
        RoadmapStep(
          title: 'Machine Learning Basics',
          description: 'Introduction to ML algorithms',
          duration: '8-10 weeks',
          topics: [
            'Supervised learning',
            'Unsupervised learning',
            'Linear regression',
            'Classification',
            'Decision trees',
            'Model evaluation',
          ],
          resources: [
            'Scikit-learn Docs',
            'Andrew Ng Course',
            'Hands-On ML Book',
          ],
        ),
        RoadmapStep(
          title: 'Deep Learning',
          description: 'Neural networks and deep learning',
          duration: '8-10 weeks',
          topics: [
            'Neural networks',
            'TensorFlow/PyTorch',
            'CNNs for images',
            'RNNs for sequences',
            'Transfer learning',
          ],
          resources: [
            'Fast.ai',
            'TensorFlow Tutorials',
            'Deep Learning Specialization',
          ],
        ),
        RoadmapStep(
          title: 'Projects & Portfolio',
          description: 'Build real-world projects',
          duration: '6-8 weeks',
          topics: [
            'Kaggle competitions',
            'End-to-end projects',
            'Model deployment',
            'Portfolio website',
            'GitHub projects',
          ],
          resources: [
            'Kaggle',
            'GitHub',
            'Medium Articles',
          ],
        ),
      ],
    ),

    // DevOps
    TechRoadmap(
      title: 'DevOps Engineer',
      description: 'Master deployment and infrastructure',
      category: 'DevOps',
      duration: '6-8 months',
      icon: Icons.cloud,
      color: Colors.orange,
      steps: [
        RoadmapStep(
          title: 'Linux & Command Line',
          description: 'Master Linux fundamentals',
          duration: '3-4 weeks',
          topics: [
            'Linux basics',
            'Shell scripting',
            'File permissions',
            'Process management',
            'Networking basics',
          ],
          resources: [
            'Linux Journey',
            'OverTheWire',
            'Linux Command Line Book',
          ],
        ),
        RoadmapStep(
          title: 'Version Control',
          description: 'Git and GitHub mastery',
          duration: '2-3 weeks',
          topics: [
            'Git basics',
            'Branching strategies',
            'Pull requests',
            'Git workflows',
            'GitHub Actions',
          ],
          resources: [
            'Pro Git Book',
            'GitHub Learning Lab',
            'Atlassian Git Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Containerization',
          description: 'Docker and container orchestration',
          duration: '4-6 weeks',
          topics: [
            'Docker basics',
            'Dockerfiles',
            'Docker Compose',
            'Container networking',
            'Docker Hub',
          ],
          resources: [
            'Docker Documentation',
            'Docker Mastery Course',
            'Play with Docker',
          ],
        ),
        RoadmapStep(
          title: 'CI/CD Pipelines',
          description: 'Automate deployment',
          duration: '4-5 weeks',
          topics: [
            'Jenkins',
            'GitHub Actions',
            'GitLab CI',
            'Pipeline design',
            'Automated testing',
          ],
          resources: [
            'Jenkins Documentation',
            'GitHub Actions Docs',
            'CI/CD Best Practices',
          ],
        ),
        RoadmapStep(
          title: 'Cloud Platforms',
          description: 'AWS, Azure, or GCP',
          duration: '8-10 weeks',
          topics: [
            'Cloud fundamentals',
            'EC2/Compute',
            'S3/Storage',
            'Networking',
            'IAM and security',
          ],
          resources: [
            'AWS Free Tier',
            'A Cloud Guru',
            'Cloud Academy',
          ],
        ),
        RoadmapStep(
          title: 'Monitoring & Logging',
          description: 'Monitor applications',
          duration: '3-4 weeks',
          topics: [
            'Prometheus',
            'Grafana',
            'ELK Stack',
            'Application monitoring',
            'Log aggregation',
          ],
          resources: [
            'Prometheus Docs',
            'Grafana Tutorials',
            'Elastic Documentation',
          ],
        ),
      ],
    ),

    // UI/UX Design
    TechRoadmap(
      title: 'UI/UX Designer',
      description: 'Design beautiful user experiences',
      category: 'Design',
      duration: '5-6 months',
      icon: Icons.design_services,
      color: Colors.pink,
      steps: [
        RoadmapStep(
          title: 'Design Fundamentals',
          description: 'Learn design principles',
          duration: '3-4 weeks',
          topics: [
            'Color theory',
            'Typography',
            'Layout and composition',
            'Visual hierarchy',
            'Design systems',
          ],
          resources: [
            'Refactoring UI',
            'Design Course',
            'Material Design',
          ],
        ),
        RoadmapStep(
          title: 'Design Tools',
          description: 'Master design software',
          duration: '4-6 weeks',
          topics: [
            'Figma basics',
            'Components and variants',
            'Auto layout',
            'Prototyping',
            'Collaboration',
          ],
          resources: [
            'Figma Learn',
            'Figma Community',
            'YouTube Tutorials',
          ],
        ),
        RoadmapStep(
          title: 'User Research',
          description: 'Understand your users',
          duration: '3-4 weeks',
          topics: [
            'User interviews',
            'Surveys',
            'Personas',
            'User journey maps',
            'Usability testing',
          ],
          resources: [
            'Nielsen Norman Group',
            'UX Research Methods',
            'User Interviews Guide',
          ],
        ),
        RoadmapStep(
          title: 'Wireframing & Prototyping',
          description: 'Create interactive prototypes',
          duration: '4-5 weeks',
          topics: [
            'Low-fidelity wireframes',
            'High-fidelity mockups',
            'Interactive prototypes',
            'Micro-interactions',
            'Animation',
          ],
          resources: [
            'Figma Prototyping',
            'Principle App',
            'Framer',
          ],
        ),
        RoadmapStep(
          title: 'Portfolio & Projects',
          description: 'Build your portfolio',
          duration: '6-8 weeks',
          topics: [
            'Case studies',
            'Portfolio website',
            'Behance/Dribbble',
            'Real client projects',
            'Design challenges',
          ],
          resources: [
            'Behance',
            'Dribbble',
            'Daily UI Challenge',
          ],
        ),
      ],
    ),

    // Android Development (Detailed)
    TechRoadmap(
      title: 'Android Developer',
      description: 'Complete Android development with Kotlin',
      category: 'Mobile Development',
      duration: '7-9 months',
      icon: Icons.android,
      color: Colors.lightGreen,
      steps: [
        RoadmapStep(
          title: 'Java/Kotlin Basics',
          description: 'Learn Kotlin programming language',
          duration: '4-5 weeks',
          topics: [
            'Kotlin syntax',
            'Variables and data types',
            'Control flow',
            'Functions',
            'OOP in Kotlin',
            'Null safety',
            'Collections',
            'Lambda expressions',
          ],
          resources: [
            'Kotlin Koans',
            'Kotlin Documentation',
            'Kotlin for Android Developers',
          ],
        ),
        RoadmapStep(
          title: 'Android Studio & Gradle',
          description: 'Setup development environment',
          duration: '1 week',
          topics: [
            'Android Studio IDE',
            'Project structure',
            'Gradle build system',
            'Dependencies management',
            'Build variants',
          ],
          resources: [
            'Android Studio Guide',
            'Gradle Documentation',
            'Android Developer Setup',
          ],
        ),
        RoadmapStep(
          title: 'Android Fundamentals',
          description: 'Core Android concepts',
          duration: '6-8 weeks',
          topics: [
            'Activities and lifecycle',
            'Fragments',
            'Intents',
            'Views and layouts',
            'RecyclerView',
            'Material Design',
            'Resources and assets',
            'Permissions',
          ],
          resources: [
            'Android Developer Guides',
            'Udacity Android Course',
            'Android Basics Codelabs',
          ],
        ),
        RoadmapStep(
          title: 'Jetpack Architecture Components',
          description: 'Modern Android architecture',
          duration: '6-8 weeks',
          topics: [
            'ViewModel',
            'LiveData',
            'Room Database',
            'Navigation Component',
            'WorkManager',
            'Data Binding',
            'Paging',
            'MVVM pattern',
          ],
          resources: [
            'Android Jetpack',
            'Architecture Components Codelabs',
            'Android Architecture Guide',
          ],
        ),
        RoadmapStep(
          title: 'Networking & APIs',
          description: 'Connect to backend services',
          duration: '3-4 weeks',
          topics: [
            'Retrofit',
            'OkHttp',
            'REST APIs',
            'JSON parsing (Gson/Moshi)',
            'Coroutines for async',
            'Error handling',
          ],
          resources: [
            'Retrofit Documentation',
            'Networking Codelab',
            'Kotlin Coroutines Guide',
          ],
        ),
        RoadmapStep(
          title: 'Dependency Injection',
          description: 'Learn Hilt/Dagger',
          duration: '2-3 weeks',
          topics: [
            'Dependency injection concepts',
            'Hilt basics',
            'Modules and components',
            'Scopes',
            'Testing with DI',
          ],
          resources: [
            'Hilt Documentation',
            'Dagger Guide',
            'DI Best Practices',
          ],
        ),
        RoadmapStep(
          title: 'Testing',
          description: 'Write tests for Android',
          duration: '3-4 weeks',
          topics: [
            'Unit testing with JUnit',
            'Mockito',
            'Espresso UI tests',
            'Test-driven development',
            'Integration tests',
          ],
          resources: [
            'Android Testing Codelabs',
            'Testing Guide',
            'Espresso Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Advanced Topics',
          description: 'Advanced Android features',
          duration: '4-6 weeks',
          topics: [
            'Custom views',
            'Animations',
            'Services',
            'Broadcast receivers',
            'Content providers',
            'Firebase integration',
            'Push notifications',
          ],
          resources: [
            'Advanced Android Development',
            'Firebase Android',
            'Custom Views Guide',
          ],
        ),
        RoadmapStep(
          title: 'Publishing',
          description: 'Deploy to Play Store',
          duration: '1-2 weeks',
          topics: [
            'App signing',
            'ProGuard/R8',
            'Play Store listing',
            'App bundles',
            'Release management',
          ],
          resources: [
            'Play Console Guide',
            'Publishing Checklist',
            'App Bundle Guide',
          ],
        ),
      ],
    ),

    // iOS Development
    TechRoadmap(
      title: 'iOS Developer',
      description: 'Build iOS apps with Swift and SwiftUI',
      category: 'Mobile Development',
      duration: '7-9 months',
      icon: Icons.apple,
      color: Colors.grey,
      steps: [
        RoadmapStep(
          title: 'Swift Basics',
          description: 'Learn Swift programming',
          duration: '4-5 weeks',
          topics: [
            'Swift syntax',
            'Variables and constants',
            'Optionals',
            'Control flow',
            'Functions and closures',
            'OOP in Swift',
            'Protocols',
            'Generics',
          ],
          resources: [
            'Swift Documentation',
            'Swift Playgrounds',
            '100 Days of Swift',
          ],
        ),
        RoadmapStep(
          title: 'Xcode & Interface Builder',
          description: 'Master iOS development tools',
          duration: '1-2 weeks',
          topics: [
            'Xcode IDE',
            'Interface Builder',
            'Storyboards',
            'Auto Layout',
            'Simulator',
          ],
          resources: [
            'Xcode Documentation',
            'Apple Developer',
            'Xcode Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'UIKit Fundamentals',
          description: 'Build UIs with UIKit',
          duration: '6-8 weeks',
          topics: [
            'View controllers',
            'UIView hierarchy',
            'Table views',
            'Collection views',
            'Navigation',
            'Tab bars',
            'Gestures',
          ],
          resources: [
            'UIKit Documentation',
            'iOS App Dev Tutorials',
            'Hacking with Swift',
          ],
        ),
        RoadmapStep(
          title: 'SwiftUI',
          description: 'Modern declarative UI',
          duration: '6-8 weeks',
          topics: [
            'SwiftUI basics',
            'Views and modifiers',
            'State management',
            'Bindings',
            'Lists and navigation',
            'Animations',
            'Combine framework',
          ],
          resources: [
            'SwiftUI Tutorials',
            '100 Days of SwiftUI',
            'SwiftUI by Example',
          ],
        ),
        RoadmapStep(
          title: 'Data Persistence',
          description: 'Store data locally',
          duration: '3-4 weeks',
          topics: [
            'UserDefaults',
            'Core Data',
            'File system',
            'Keychain',
            'SQLite',
          ],
          resources: [
            'Core Data Tutorial',
            'Data Persistence Guide',
            'Keychain Services',
          ],
        ),
        RoadmapStep(
          title: 'Networking',
          description: 'Connect to APIs',
          duration: '3-4 weeks',
          topics: [
            'URLSession',
            'REST APIs',
            'JSON decoding',
            'Alamofire',
            'Async/await',
            'Error handling',
          ],
          resources: [
            'URLSession Guide',
            'Networking in Swift',
            'Alamofire Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Architecture Patterns',
          description: 'Structure your app',
          duration: '3-4 weeks',
          topics: [
            'MVC',
            'MVVM',
            'Coordinator pattern',
            'Dependency injection',
            'Clean architecture',
          ],
          resources: [
            'iOS Architecture Patterns',
            'MVVM Tutorial',
            'Clean Swift',
          ],
        ),
        RoadmapStep(
          title: 'Testing',
          description: 'Test iOS apps',
          duration: '2-3 weeks',
          topics: [
            'XCTest',
            'Unit testing',
            'UI testing',
            'Test-driven development',
            'Mocking',
          ],
          resources: [
            'XCTest Documentation',
            'iOS Testing Guide',
            'TDD in Swift',
          ],
        ),
        RoadmapStep(
          title: 'App Store Deployment',
          description: 'Publish to App Store',
          duration: '1-2 weeks',
          topics: [
            'App Store Connect',
            'Certificates and provisioning',
            'TestFlight',
            'App review guidelines',
            'Release management',
          ],
          resources: [
            'App Store Connect Guide',
            'Distribution Guide',
            'App Review Guidelines',
          ],
        ),
      ],
    ),

    // Cybersecurity (Detailed)
    TechRoadmap(
      title: 'Cybersecurity Specialist',
      description: 'Complete cybersecurity and ethical hacking path',
      category: 'Cybersecurity',
      duration: '10-14 months',
      icon: Icons.security,
      color: Colors.red,
      steps: [
        RoadmapStep(
          title: 'IT Fundamentals',
          description: 'Basic IT knowledge',
          duration: '3-4 weeks',
          topics: [
            'Computer hardware',
            'Operating systems',
            'Software basics',
            'Troubleshooting',
            'IT support',
          ],
          resources: [
            'CompTIA IT Fundamentals',
            'Professor Messer',
            'IT Basics Course',
          ],
        ),
        RoadmapStep(
          title: 'Networking Fundamentals',
          description: 'Understand computer networks',
          duration: '6-8 weeks',
          topics: [
            'OSI model',
            'TCP/IP protocol suite',
            'IP addressing and subnetting',
            'DNS and DHCP',
            'Routing and switching',
            'Network devices',
            'Wireless networking',
          ],
          resources: [
            'CompTIA Network+',
            'Cisco CCNA',
            'NetworkChuck YouTube',
          ],
        ),
        RoadmapStep(
          title: 'Linux Administration',
          description: 'Master Linux for security',
          duration: '6-8 weeks',
          topics: [
            'Linux distributions',
            'Command line basics',
            'File system',
            'User management',
            'Permissions',
            'Shell scripting',
            'Package management',
            'System services',
          ],
          resources: [
            'Linux Journey',
            'OverTheWire Bandit',
            'Linux Command Line Book',
          ],
        ),
        RoadmapStep(
          title: 'Programming for Security',
          description: 'Learn Python and scripting',
          duration: '6-8 weeks',
          topics: [
            'Python basics',
            'Scripting',
            'Automation',
            'Network programming',
            'Web scraping',
            'Security tools development',
          ],
          resources: [
            'Automate the Boring Stuff',
            'Black Hat Python',
            'Python for Cybersecurity',
          ],
        ),
        RoadmapStep(
          title: 'Security Fundamentals',
          description: 'Core security concepts',
          duration: '4-6 weeks',
          topics: [
            'CIA triad',
            'Authentication vs Authorization',
            'Encryption basics',
            'Hashing',
            'Digital signatures',
            'PKI',
            'Security policies',
          ],
          resources: [
            'CompTIA Security+',
            'Cybrary Security+',
            'Security Fundamentals',
          ],
        ),
        RoadmapStep(
          title: 'Web Application Security',
          description: 'Secure web applications',
          duration: '6-8 weeks',
          topics: [
            'OWASP Top 10',
            'SQL injection',
            'XSS attacks',
            'CSRF',
            'Authentication flaws',
            'Session management',
            'Burp Suite',
          ],
          resources: [
            'OWASP WebGoat',
            'PortSwigger Web Security Academy',
            'HackTheBox Web Challenges',
          ],
        ),
        RoadmapStep(
          title: 'Penetration Testing',
          description: 'Learn ethical hacking',
          duration: '10-12 weeks',
          topics: [
            'Reconnaissance',
            'Scanning and enumeration',
            'Vulnerability assessment',
            'Exploitation',
            'Post-exploitation',
            'Metasploit',
            'Nmap',
            'Report writing',
          ],
          resources: [
            'TryHackMe',
            'HackTheBox',
            'PentesterLab',
            'CEH Course',
          ],
        ),
        RoadmapStep(
          title: 'Network Security',
          description: 'Secure networks',
          duration: '4-6 weeks',
          topics: [
            'Firewalls',
            'IDS/IPS',
            'VPN',
            'Network segmentation',
            'Wireless security',
            'Network monitoring',
          ],
          resources: [
            'Network Security Course',
            'Wireshark Tutorial',
            'Firewall Configuration',
          ],
        ),
        RoadmapStep(
          title: 'Incident Response',
          description: 'Handle security incidents',
          duration: '3-4 weeks',
          topics: [
            'Incident response process',
            'Forensics basics',
            'Log analysis',
            'Malware analysis',
            'Threat hunting',
          ],
          resources: [
            'SANS Incident Response',
            'Digital Forensics Guide',
            'Incident Response Playbook',
          ],
        ),
        RoadmapStep(
          title: 'Certifications',
          description: 'Get certified',
          duration: '8-12 weeks',
          topics: [
            'CEH (Certified Ethical Hacker)',
            'OSCP (Offensive Security)',
            'CompTIA Security+',
            'CISSP (for advanced)',
          ],
          resources: [
            'EC-Council CEH',
            'Offensive Security',
            'CompTIA Certification',
          ],
        ),
      ],
    ),

    // Blockchain Development
    TechRoadmap(
      title: 'Blockchain Developer',
      description: 'Build decentralized applications',
      category: 'Blockchain',
      duration: '6-8 months',
      icon: Icons.currency_bitcoin,
      color: Colors.amber,
      steps: [
        RoadmapStep(
          title: 'Blockchain Basics',
          description: 'Understand blockchain technology',
          duration: '2-3 weeks',
          topics: [
            'What is blockchain?',
            'Distributed ledger',
            'Consensus mechanisms',
            'Cryptography basics',
            'Bitcoin basics',
            'Ethereum basics',
          ],
          resources: [
            'Blockchain Basics Course',
            'Bitcoin Whitepaper',
            'Ethereum Whitepaper',
          ],
        ),
        RoadmapStep(
          title: 'Solidity Programming',
          description: 'Learn smart contract language',
          duration: '6-8 weeks',
          topics: [
            'Solidity syntax',
            'Data types',
            'Functions',
            'Modifiers',
            'Events',
            'Inheritance',
            'Libraries',
            'Security patterns',
          ],
          resources: [
            'Solidity Documentation',
            'CryptoZombies',
            'Solidity by Example',
          ],
        ),
        RoadmapStep(
          title: 'Smart Contracts',
          description: 'Build and deploy contracts',
          duration: '6-8 weeks',
          topics: [
            'ERC-20 tokens',
            'ERC-721 NFTs',
            'Contract deployment',
            'Gas optimization',
            'Testing contracts',
            'Hardhat/Truffle',
          ],
          resources: [
            'Hardhat Documentation',
            'OpenZeppelin Contracts',
            'Smart Contract Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Web3 Development',
          description: 'Build dApps',
          duration: '4-6 weeks',
          topics: [
            'Web3.js',
            'Ethers.js',
            'MetaMask integration',
            'Frontend for dApps',
            'IPFS',
            'The Graph',
          ],
          resources: [
            'Web3.js Documentation',
            'Ethers.js Docs',
            'dApp University',
          ],
        ),
        RoadmapStep(
          title: 'DeFi & NFTs',
          description: 'Advanced blockchain apps',
          duration: '4-6 weeks',
          topics: [
            'DeFi protocols',
            'Liquidity pools',
            'Yield farming',
            'NFT marketplaces',
            'DAOs',
          ],
          resources: [
            'DeFi Developer Roadmap',
            'NFT School',
            'Uniswap Documentation',
          ],
        ),
      ],
    ),

    // Game Development
    TechRoadmap(
      title: 'Game Developer',
      description: 'Create games with Unity or Unreal',
      category: 'Game Development',
      duration: '8-12 months',
      icon: Icons.sports_esports,
      color: Colors.deepPurple,
      steps: [
        RoadmapStep(
          title: 'Programming Basics',
          description: 'Learn C# or C++',
          duration: '6-8 weeks',
          topics: [
            'C# syntax (for Unity)',
            'OOP concepts',
            'Data structures',
            'Algorithms',
            'Design patterns',
          ],
          resources: [
            'C# Documentation',
            'Unity Learn',
            'Brackeys YouTube',
          ],
        ),
        RoadmapStep(
          title: 'Unity Basics',
          description: 'Learn Unity engine',
          duration: '6-8 weeks',
          topics: [
            'Unity interface',
            'GameObjects',
            'Components',
            'Prefabs',
            'Scenes',
            'Physics',
            'Input system',
          ],
          resources: [
            'Unity Learn Platform',
            'Unity Documentation',
            'Brackeys Tutorials',
          ],
        ),
        RoadmapStep(
          title: '2D Game Development',
          description: 'Create 2D games',
          duration: '6-8 weeks',
          topics: [
            'Sprites',
            '2D physics',
            'Tilemaps',
            'Animation',
            'Particle systems',
            'UI design',
          ],
          resources: [
            'Unity 2D Tutorial',
            '2D Game Kit',
            'Pixel Art Course',
          ],
        ),
        RoadmapStep(
          title: '3D Game Development',
          description: 'Build 3D games',
          duration: '8-10 weeks',
          topics: [
            '3D modeling basics',
            'Materials and shaders',
            '3D physics',
            'Lighting',
            'Camera control',
            'Terrain',
          ],
          resources: [
            'Unity 3D Tutorial',
            'Blender Basics',
            '3D Game Kit',
          ],
        ),
        RoadmapStep(
          title: 'Game Design',
          description: 'Learn game design principles',
          duration: '4-6 weeks',
          topics: [
            'Game mechanics',
            'Level design',
            'Player experience',
            'Balancing',
            'Storytelling',
          ],
          resources: [
            'Game Design Course',
            'Extra Credits YouTube',
            'The Art of Game Design',
          ],
        ),
        RoadmapStep(
          title: 'Audio & Polish',
          description: 'Add sound and polish',
          duration: '3-4 weeks',
          topics: [
            'Sound effects',
            'Music',
            'Audio mixing',
            'Particle effects',
            'Post-processing',
          ],
          resources: [
            'Unity Audio',
            'Freesound.org',
            'Game Audio Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Publishing',
          description: 'Release your game',
          duration: '2-3 weeks',
          topics: [
            'Build settings',
            'Platform-specific builds',
            'Steam publishing',
            'Mobile stores',
            'Marketing basics',
          ],
          resources: [
            'Unity Publishing Guide',
            'Steam Direct',
            'Indie Game Marketing',
          ],
        ),
      ],
    ),

    // Cloud Engineer
    TechRoadmap(
      title: 'Cloud Engineer (AWS)',
      description: 'Master cloud computing with AWS',
      category: 'Cloud',
      duration: '6-9 months',
      icon: Icons.cloud_circle,
      color: Colors.orange,
      steps: [
        RoadmapStep(
          title: 'Cloud Fundamentals',
          description: 'Understand cloud computing',
          duration: '2-3 weeks',
          topics: [
            'What is cloud computing?',
            'IaaS, PaaS, SaaS',
            'Public vs Private cloud',
            'Cloud benefits',
            'AWS overview',
          ],
          resources: [
            'AWS Cloud Practitioner',
            'Cloud Computing Basics',
            'AWS Free Tier',
          ],
        ),
        RoadmapStep(
          title: 'AWS Core Services',
          description: 'Learn essential AWS services',
          duration: '6-8 weeks',
          topics: [
            'EC2 (Compute)',
            'S3 (Storage)',
            'VPC (Networking)',
            'IAM (Security)',
            'RDS (Databases)',
            'Lambda (Serverless)',
          ],
          resources: [
            'AWS Documentation',
            'A Cloud Guru',
            'AWS Training',
          ],
        ),
        RoadmapStep(
          title: 'Networking in AWS',
          description: 'Master AWS networking',
          duration: '3-4 weeks',
          topics: [
            'VPC design',
            'Subnets',
            'Route tables',
            'Internet Gateway',
            'NAT Gateway',
            'Security groups',
            'NACLs',
          ],
          resources: [
            'AWS VPC Guide',
            'Networking Specialty',
            'VPC Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Security & IAM',
          description: 'Secure AWS resources',
          duration: '3-4 weeks',
          topics: [
            'IAM users and roles',
            'Policies',
            'MFA',
            'KMS encryption',
            'Secrets Manager',
            'Security best practices',
          ],
          resources: [
            'AWS Security',
            'IAM Best Practices',
            'Security Specialty',
          ],
        ),
        RoadmapStep(
          title: 'Serverless Architecture',
          description: 'Build serverless apps',
          duration: '4-6 weeks',
          topics: [
            'Lambda functions',
            'API Gateway',
            'DynamoDB',
            'S3 events',
            'Step Functions',
            'SAM/Serverless Framework',
          ],
          resources: [
            'AWS Lambda Guide',
            'Serverless Framework',
            'Serverless Patterns',
          ],
        ),
        RoadmapStep(
          title: 'Containers & Orchestration',
          description: 'Docker and ECS/EKS',
          duration: '4-6 weeks',
          topics: [
            'Docker basics',
            'ECS (Elastic Container Service)',
            'EKS (Kubernetes)',
            'ECR (Container Registry)',
            'Fargate',
          ],
          resources: [
            'AWS ECS Guide',
            'EKS Workshop',
            'Docker Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Monitoring & Logging',
          description: 'Monitor AWS resources',
          duration: '2-3 weeks',
          topics: [
            'CloudWatch',
            'CloudTrail',
            'X-Ray',
            'Alarms',
            'Dashboards',
            'Log analysis',
          ],
          resources: [
            'CloudWatch Documentation',
            'Monitoring Best Practices',
            'AWS Observability',
          ],
        ),
        RoadmapStep(
          title: 'Infrastructure as Code',
          description: 'Automate with IaC',
          duration: '4-6 weeks',
          topics: [
            'CloudFormation',
            'Terraform',
            'CDK',
            'Template design',
            'Stack management',
          ],
          resources: [
            'CloudFormation Guide',
            'Terraform AWS',
            'AWS CDK Workshop',
          ],
        ),
        RoadmapStep(
          title: 'AWS Certifications',
          description: 'Get certified',
          duration: '6-8 weeks',
          topics: [
            'Solutions Architect Associate',
            'Developer Associate',
            'SysOps Administrator',
          ],
          resources: [
            'AWS Certification',
            'Practice Exams',
            'Study Guides',
          ],
        ),
      ],
    ),

    // Computer Science Fundamentals
    TechRoadmap(
      title: 'Computer Science Fundamentals',
      description: 'Core CS concepts every developer should know',
      category: 'Programming',
      duration: '6-8 months',
      icon: Icons.school,
      color: Colors.teal,
      steps: [
        RoadmapStep(
          title: 'Programming Basics',
          description: 'Learn to code with Python',
          duration: '4-6 weeks',
          topics: [
            'Variables and data types',
            'Control structures (if/else, loops)',
            'Functions',
            'Basic input/output',
            'Problem solving',
            'Debugging',
          ],
          resources: [
            'CS50 Introduction',
            'Python for Beginners',
            'Codecademy Python',
          ],
        ),
        RoadmapStep(
          title: 'Data Structures',
          description: 'Essential data structures',
          duration: '6-8 weeks',
          topics: [
            'Arrays and strings',
            'Linked lists',
            'Stacks and queues',
            'Trees (Binary, BST, AVL)',
            'Graphs',
            'Hash tables',
            'Heaps',
            'Tries',
          ],
          resources: [
            'GeeksforGeeks DS',
            'Data Structures Course',
            'Visualgo.net',
          ],
        ),
        RoadmapStep(
          title: 'Algorithms',
          description: 'Master common algorithms',
          duration: '6-8 weeks',
          topics: [
            'Sorting (Quick, Merge, Heap)',
            'Searching (Binary search)',
            'Recursion',
            'Dynamic programming',
            'Greedy algorithms',
            'Backtracking',
            'Graph algorithms (BFS, DFS, Dijkstra)',
          ],
          resources: [
            'Introduction to Algorithms',
            'LeetCode',
            'Algorithm Visualizer',
          ],
        ),
        RoadmapStep(
          title: 'Time & Space Complexity',
          description: 'Analyze algorithm efficiency',
          duration: '2-3 weeks',
          topics: [
            'Big O notation',
            'Time complexity analysis',
            'Space complexity',
            'Best, average, worst case',
            'Amortized analysis',
          ],
          resources: [
            'Big O Cheat Sheet',
            'Complexity Analysis Guide',
            'MIT OCW Algorithms',
          ],
        ),
        RoadmapStep(
          title: 'Object-Oriented Programming',
          description: 'OOP principles',
          duration: '4-5 weeks',
          topics: [
            'Classes and objects',
            'Encapsulation',
            'Inheritance',
            'Polymorphism',
            'Abstraction',
            'SOLID principles',
            'Design patterns',
          ],
          resources: [
            'OOP Concepts',
            'Design Patterns Book',
            'Refactoring Guru',
          ],
        ),
        RoadmapStep(
          title: 'Operating Systems',
          description: 'OS fundamentals',
          duration: '4-6 weeks',
          topics: [
            'Processes and threads',
            'Memory management',
            'File systems',
            'Scheduling',
            'Deadlocks',
            'Synchronization',
          ],
          resources: [
            'Operating System Concepts',
            'OS Course',
            'Linux Kernel',
          ],
        ),
        RoadmapStep(
          title: 'Computer Networks',
          description: 'Networking basics',
          duration: '4-5 weeks',
          topics: [
            'OSI model',
            'TCP/IP',
            'HTTP/HTTPS',
            'DNS',
            'Sockets',
            'Network security',
          ],
          resources: [
            'Computer Networking',
            'Network Fundamentals',
            'Beej\'s Guide to Network',
          ],
        ),
        RoadmapStep(
          title: 'Databases',
          description: 'Database concepts',
          duration: '4-5 weeks',
          topics: [
            'Relational databases',
            'SQL',
            'Normalization',
            'Transactions (ACID)',
            'Indexing',
            'NoSQL basics',
          ],
          resources: [
            'Database Systems',
            'SQL Tutorial',
            'Database Design',
          ],
        ),
      ],
    ),

    // QA Engineer / Software Tester
    TechRoadmap(
      title: 'QA Engineer',
      description: 'Software testing and quality assurance',
      category: 'Testing',
      duration: '5-7 months',
      icon: Icons.bug_report,
      color: Colors.brown,
      steps: [
        RoadmapStep(
          title: 'Testing Fundamentals',
          description: 'Learn testing basics',
          duration: '3-4 weeks',
          topics: [
            'What is software testing?',
            'Testing principles',
            'SDLC and STLC',
            'Test levels',
            'Test types',
            'Bug life cycle',
          ],
          resources: [
            'ISTQB Foundation',
            'Software Testing Help',
            'Guru99 Testing',
          ],
        ),
        RoadmapStep(
          title: 'Manual Testing',
          description: 'Master manual testing',
          duration: '4-6 weeks',
          topics: [
            'Test case design',
            'Test execution',
            'Bug reporting',
            'Test documentation',
            'Exploratory testing',
            'Regression testing',
          ],
          resources: [
            'Manual Testing Course',
            'Test Case Writing',
            'Bug Tracking Tools',
          ],
        ),
        RoadmapStep(
          title: 'Test Automation Basics',
          description: 'Introduction to automation',
          duration: '2-3 weeks',
          topics: [
            'When to automate',
            'Automation frameworks',
            'Test automation pyramid',
            'CI/CD basics',
          ],
          resources: [
            'Test Automation University',
            'Automation Best Practices',
            'Framework Design',
          ],
        ),
        RoadmapStep(
          title: 'Programming for QA',
          description: 'Learn programming',
          duration: '6-8 weeks',
          topics: [
            'Python/Java basics',
            'OOP concepts',
            'Data structures',
            'Version control (Git)',
          ],
          resources: [
            'Python for Testers',
            'Java Programming',
            'Git for QA',
          ],
        ),
        RoadmapStep(
          title: 'Selenium WebDriver',
          description: 'Web automation with Selenium',
          duration: '6-8 weeks',
          topics: [
            'Selenium basics',
            'Locators',
            'WebDriver commands',
            'Page Object Model',
            'TestNG/JUnit',
            'Data-driven testing',
          ],
          resources: [
            'Selenium Documentation',
            'Selenium Tutorial',
            'POM Design Pattern',
          ],
        ),
        RoadmapStep(
          title: 'API Testing',
          description: 'Test REST APIs',
          duration: '3-4 weeks',
          topics: [
            'REST API basics',
            'Postman',
            'REST Assured',
            'API test automation',
            'JSON/XML',
          ],
          resources: [
            'Postman Learning',
            'REST Assured Tutorial',
            'API Testing Guide',
          ],
        ),
        RoadmapStep(
          title: 'Mobile Testing',
          description: 'Test mobile applications',
          duration: '3-4 weeks',
          topics: [
            'Mobile testing basics',
            'Appium',
            'Android/iOS testing',
            'Mobile automation',
          ],
          resources: [
            'Appium Documentation',
            'Mobile Testing Guide',
            'Appium Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Performance Testing',
          description: 'Load and performance testing',
          duration: '3-4 weeks',
          topics: [
            'Performance testing types',
            'JMeter',
            'Load testing',
            'Stress testing',
            'Performance metrics',
          ],
          resources: [
            'JMeter Tutorial',
            'Performance Testing Guide',
            'Load Testing Best Practices',
          ],
        ),
        RoadmapStep(
          title: 'CI/CD & DevOps for QA',
          description: 'Integrate testing in CI/CD',
          duration: '2-3 weeks',
          topics: [
            'Jenkins',
            'GitHub Actions',
            'Docker basics',
            'Test automation in CI/CD',
          ],
          resources: [
            'Jenkins for QA',
            'CI/CD Pipeline',
            'DevOps for Testers',
          ],
        ),
      ],
    ),

    // Product Manager
    TechRoadmap(
      title: 'Product Manager',
      description: 'Build and manage successful products',
      category: 'Product Management',
      duration: '6-8 months',
      icon: Icons.inventory,
      color: Colors.deepOrange,
      steps: [
        RoadmapStep(
          title: 'Product Management Basics',
          description: 'Understand PM role',
          duration: '2-3 weeks',
          topics: [
            'What is product management?',
            'PM responsibilities',
            'Product lifecycle',
            'Stakeholder management',
            'Product vision',
          ],
          resources: [
            'Product School',
            'Pragmatic Institute',
            'Product Management 101',
          ],
        ),
        RoadmapStep(
          title: 'User Research',
          description: 'Understand your users',
          duration: '4-5 weeks',
          topics: [
            'User interviews',
            'Surveys and questionnaires',
            'User personas',
            'Jobs to be Done',
            'Customer journey mapping',
            'Usability testing',
          ],
          resources: [
            'User Research Guide',
            'JTBD Framework',
            'Nielsen Norman Group',
          ],
        ),
        RoadmapStep(
          title: 'Product Strategy',
          description: 'Define product strategy',
          duration: '4-6 weeks',
          topics: [
            'Market analysis',
            'Competitive analysis',
            'Value proposition',
            'Product positioning',
            'Go-to-market strategy',
            'OKRs and KPIs',
          ],
          resources: [
            'Good Strategy Bad Strategy',
            'Product Strategy Guide',
            'OKR Framework',
          ],
        ),
        RoadmapStep(
          title: 'Product Discovery',
          description: 'Discover what to build',
          duration: '3-4 weeks',
          topics: [
            'Problem validation',
            'Solution validation',
            'Prototyping',
            'MVP definition',
            'Hypothesis testing',
          ],
          resources: [
            'Inspired by Marty Cagan',
            'Lean Startup',
            'Product Discovery Guide',
          ],
        ),
        RoadmapStep(
          title: 'Roadmapping & Prioritization',
          description: 'Plan product development',
          duration: '3-4 weeks',
          topics: [
            'Product roadmaps',
            'Prioritization frameworks (RICE, MoSCoW)',
            'Feature prioritization',
            'Release planning',
            'Backlog management',
          ],
          resources: [
            'Product Roadmap Guide',
            'Prioritization Techniques',
            'Roadmapping Tools',
          ],
        ),
        RoadmapStep(
          title: 'Agile & Scrum',
          description: 'Work with development teams',
          duration: '3-4 weeks',
          topics: [
            'Agile principles',
            'Scrum framework',
            'User stories',
            'Sprint planning',
            'Backlog refinement',
            'Retrospectives',
          ],
          resources: [
            'Scrum Guide',
            'Agile Manifesto',
            'User Story Mapping',
          ],
        ),
        RoadmapStep(
          title: 'Product Analytics',
          description: 'Measure product success',
          duration: '4-5 weeks',
          topics: [
            'Analytics tools (Google Analytics, Mixpanel)',
            'Metrics and KPIs',
            'A/B testing',
            'Funnel analysis',
            'Cohort analysis',
            'Data-driven decisions',
          ],
          resources: [
            'Product Analytics Guide',
            'Google Analytics Course',
            'Mixpanel Academy',
          ],
        ),
        RoadmapStep(
          title: 'Technical Knowledge',
          description: 'Understand technology',
          duration: '4-6 weeks',
          topics: [
            'Software development basics',
            'APIs and integrations',
            'Databases',
            'Cloud computing',
            'Technical trade-offs',
          ],
          resources: [
            'Technical PM Guide',
            'Software Engineering Basics',
            'API Fundamentals',
          ],
        ),
        RoadmapStep(
          title: 'Communication & Leadership',
          description: 'Lead without authority',
          duration: '4-5 weeks',
          topics: [
            'Stakeholder communication',
            'Presentation skills',
            'Influence and persuasion',
            'Conflict resolution',
            'Team collaboration',
          ],
          resources: [
            'Crucial Conversations',
            'Leadership Skills',
            'Communication Guide',
          ],
        ),
      ],
    ),

    // Machine Learning Engineer
    TechRoadmap(
      title: 'Machine Learning Engineer',
      description: 'Build and deploy ML models',
      category: 'AI/ML',
      duration: '9-12 months',
      icon: Icons.psychology,
      color: Colors.deepPurple,
      steps: [
        RoadmapStep(
          title: 'Python Programming',
          description: 'Master Python for ML',
          duration: '4-6 weeks',
          topics: [
            'Python fundamentals',
            'NumPy',
            'Pandas',
            'Matplotlib/Seaborn',
            'Jupyter Notebooks',
          ],
          resources: [
            'Python for Data Science',
            'NumPy Tutorial',
            'Pandas Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Mathematics for ML',
          description: 'Essential math concepts',
          duration: '8-10 weeks',
          topics: [
            'Linear algebra',
            'Calculus',
            'Probability',
            'Statistics',
            'Optimization',
          ],
          resources: [
            'Mathematics for ML Book',
            'Khan Academy',
            '3Blue1Brown',
          ],
        ),
        RoadmapStep(
          title: 'Machine Learning Basics',
          description: 'Core ML concepts',
          duration: '8-10 weeks',
          topics: [
            'Supervised learning',
            'Unsupervised learning',
            'Regression',
            'Classification',
            'Clustering',
            'Model evaluation',
            'Cross-validation',
          ],
          resources: [
            'Andrew Ng ML Course',
            'Scikit-learn',
            'Hands-On ML Book',
          ],
        ),
        RoadmapStep(
          title: 'Deep Learning',
          description: 'Neural networks',
          duration: '10-12 weeks',
          topics: [
            'Neural networks',
            'Backpropagation',
            'CNNs',
            'RNNs/LSTMs',
            'Transformers',
            'TensorFlow/PyTorch',
          ],
          resources: [
            'Deep Learning Specialization',
            'Fast.ai',
            'PyTorch Tutorials',
          ],
        ),
        RoadmapStep(
          title: 'Natural Language Processing',
          description: 'Work with text data',
          duration: '6-8 weeks',
          topics: [
            'Text preprocessing',
            'Word embeddings',
            'BERT and transformers',
            'Sentiment analysis',
            'Named entity recognition',
          ],
          resources: [
            'NLP Course',
            'Hugging Face',
            'spaCy Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Computer Vision',
          description: 'Work with images',
          duration: '6-8 weeks',
          topics: [
            'Image processing',
            'CNNs for vision',
            'Object detection',
            'Image segmentation',
            'Transfer learning',
          ],
          resources: [
            'Computer Vision Course',
            'OpenCV',
            'YOLO Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'MLOps',
          description: 'Deploy ML models',
          duration: '6-8 weeks',
          topics: [
            'Model deployment',
            'Docker for ML',
            'Model serving (Flask, FastAPI)',
            'ML pipelines',
            'Monitoring',
            'MLflow',
          ],
          resources: [
            'MLOps Guide',
            'MLflow Documentation',
            'Deployment Best Practices',
          ],
        ),
        RoadmapStep(
          title: 'Cloud ML Services',
          description: 'Use cloud platforms',
          duration: '4-6 weeks',
          topics: [
            'AWS SageMaker',
            'Google Cloud AI',
            'Azure ML',
            'Cloud storage',
            'Scalable training',
          ],
          resources: [
            'AWS ML Services',
            'GCP AI Platform',
            'Azure ML Studio',
          ],
        ),
      ],
    ),

    // React Native Developer
    TechRoadmap(
      title: 'React Native Developer',
      description: 'Build cross-platform mobile apps with React Native',
      category: 'Mobile Development',
      duration: '6-8 months',
      icon: Icons.phone_iphone,
      color: Colors.blueAccent,
      steps: [
        RoadmapStep(
          title: 'JavaScript Fundamentals',
          description: 'Master JavaScript',
          duration: '4-6 weeks',
          topics: [
            'ES6+ features',
            'Async/await',
            'Promises',
            'Arrow functions',
            'Destructuring',
            'Modules',
          ],
          resources: [
            'JavaScript.info',
            'MDN JavaScript',
            'You Don\'t Know JS',
          ],
        ),
        RoadmapStep(
          title: 'React Basics',
          description: 'Learn React fundamentals',
          duration: '6-8 weeks',
          topics: [
            'Components',
            'Props and state',
            'Hooks',
            'Context API',
            'Lifecycle methods',
            'Event handling',
          ],
          resources: [
            'React Documentation',
            'React Tutorial',
            'Epic React',
          ],
        ),
        RoadmapStep(
          title: 'React Native Basics',
          description: 'Get started with React Native',
          duration: '4-6 weeks',
          topics: [
            'Setup and installation',
            'Core components',
            'Styling',
            'Flexbox layout',
            'Navigation',
            'Platform-specific code',
          ],
          resources: [
            'React Native Docs',
            'React Native Tutorial',
            'Expo Documentation',
          ],
        ),
        RoadmapStep(
          title: 'Navigation',
          description: 'Implement navigation',
          duration: '2-3 weeks',
          topics: [
            'React Navigation',
            'Stack navigator',
            'Tab navigator',
            'Drawer navigator',
            'Deep linking',
          ],
          resources: [
            'React Navigation Docs',
            'Navigation Tutorial',
            'Navigation Patterns',
          ],
        ),
        RoadmapStep(
          title: 'State Management',
          description: 'Manage app state',
          duration: '3-4 weeks',
          topics: [
            'Redux',
            'Redux Toolkit',
            'Context API',
            'Zustand',
            'State management patterns',
          ],
          resources: [
            'Redux Documentation',
            'Redux Toolkit',
            'State Management Guide',
          ],
        ),
        RoadmapStep(
          title: 'Networking & APIs',
          description: 'Connect to backend',
          duration: '3-4 weeks',
          topics: [
            'Fetch API',
            'Axios',
            'REST APIs',
            'GraphQL',
            'Error handling',
          ],
          resources: [
            'Networking in RN',
            'Axios Documentation',
            'GraphQL Tutorial',
          ],
        ),
        RoadmapStep(
          title: 'Local Storage',
          description: 'Store data locally',
          duration: '2-3 weeks',
          topics: [
            'AsyncStorage',
            'SQLite',
            'Realm',
            'MMKV',
            'Secure storage',
          ],
          resources: [
            'AsyncStorage Docs',
            'Realm Documentation',
            'Storage Solutions',
          ],
        ),
        RoadmapStep(
          title: 'Native Modules',
          description: 'Access native features',
          duration: '3-4 weeks',
          topics: [
            'Camera',
            'Geolocation',
            'Push notifications',
            'Biometrics',
            'Native modules',
          ],
          resources: [
            'Native Modules Guide',
            'React Native Community',
            'Platform APIs',
          ],
        ),
        RoadmapStep(
          title: 'Testing & Deployment',
          description: 'Test and publish apps',
          duration: '3-4 weeks',
          topics: [
            'Jest testing',
            'React Native Testing Library',
            'E2E testing (Detox)',
            'App Store deployment',
            'Play Store deployment',
          ],
          resources: [
            'Testing Guide',
            'Detox Documentation',
            'Deployment Guide',
          ],
        ),
      ],
    ),

    // Go (Golang) Developer
    TechRoadmap(
      title: 'Go (Golang) Developer',
      description: 'Backend development with Go',
      category: 'Programming',
      duration: '5-7 months',
      icon: Icons.code_outlined,
      color: Colors.cyan,
      steps: [
        RoadmapStep(
          title: 'Go Basics',
          description: 'Learn Go fundamentals',
          duration: '4-6 weeks',
          topics: [
            'Go syntax',
            'Variables and types',
            'Control structures',
            'Functions',
            'Packages',
            'Error handling',
          ],
          resources: [
            'Tour of Go',
            'Go by Example',
            'Effective Go',
          ],
        ),
        RoadmapStep(
          title: 'Advanced Go',
          description: 'Master Go features',
          duration: '4-6 weeks',
          topics: [
            'Structs and interfaces',
            'Goroutines',
            'Channels',
            'Concurrency patterns',
            'Context package',
            'Reflection',
          ],
          resources: [
            'Go Concurrency Patterns',
            'Advanced Go Programming',
            'Go Blog',
          ],
        ),
        RoadmapStep(
          title: 'Web Development',
          description: 'Build web services',
          duration: '6-8 weeks',
          topics: [
            'net/http package',
            'Gin framework',
            'Echo framework',
            'REST APIs',
            'Middleware',
            'Routing',
          ],
          resources: [
            'Gin Documentation',
            'Go Web Examples',
            'Building Web Apps',
          ],
        ),
        RoadmapStep(
          title: 'Database Integration',
          description: 'Work with databases',
          duration: '3-4 weeks',
          topics: [
            'database/sql',
            'PostgreSQL',
            'MongoDB',
            'GORM',
            'Migrations',
          ],
          resources: [
            'GORM Documentation',
            'Go Database Tutorial',
            'SQL in Go',
          ],
        ),
        RoadmapStep(
          title: 'Testing',
          description: 'Test Go applications',
          duration: '2-3 weeks',
          topics: [
            'testing package',
            'Table-driven tests',
            'Mocking',
            'Benchmarking',
            'Test coverage',
          ],
          resources: [
            'Go Testing Guide',
            'Testing Best Practices',
            'Testify Package',
          ],
        ),
        RoadmapStep(
          title: 'Microservices',
          description: 'Build microservices',
          duration: '4-6 weeks',
          topics: [
            'gRPC',
            'Protocol Buffers',
            'Service communication',
            'API Gateway',
            'Service discovery',
          ],
          resources: [
            'gRPC Go Tutorial',
            'Microservices in Go',
            'Go Kit',
          ],
        ),
        RoadmapStep(
          title: 'Deployment',
          description: 'Deploy Go applications',
          duration: '2-3 weeks',
          topics: [
            'Docker',
            'Kubernetes',
            'CI/CD',
            'Monitoring',
            'Logging',
          ],
          resources: [
            'Docker for Go',
            'Kubernetes Guide',
            'Deployment Best Practices',
          ],
        ),
      ],
    ),
  ];
}
